export const DEFAULT_CYLINDER_HEIGHT = 0.375;
export const DEFAULT_CYLINDER_RADIUS = 0.15;
export const DEFAULT_RADIAL_SEGMENTS = 32;

export const DEFAULT_CONE_HEIGHT = 0.25;
export const DEFAULT_CONE_RADIUS = 0.3;

export const DEFAULT_RING_INNER_RADIUS = 1;
export const DEFAULT_RING_OUTER_RADIUS = 1.25;
export const DEFAULT_RING_THETA_SEGMENTS = 96;

export const DEFAULT_CONTROLS_SEPARATION = 0.5;

export const DEFAULT_COLOR_ARROW = "#f0ff00";
export const DEFAULT_COLOR_RING = "#f0ff00";
export const DEFAULT_CONTROLS_OPACITY = 1;
